apiVersion: v1
kind: Namespace
metadata:
  name: front
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: front
    meta.helm.sh/release-namespace: front
    helm.sh/resource-policy: keep