apiVersion: v1
kind: Service
metadata:
  name: service-nginx
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.app }}
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80