apiVersion: v1
kind: PersistentVolume
metadata:
    name: my-persistent-volume-front
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: /data/my-persistent-data