apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgress-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
        - name: postgress-container
          image: {{ .Values.image }}
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: password
          volumeMounts:
            - name: {{ .Values.volumeName }}
              mountPath: /etc/secrets
      volumes:
        - name: {{ .Values.volumeName }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumeName }}