apiVersion: v1
kind: Service
metadata:
  name: service-postgress
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.app }}
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432