apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
        - name: node-container
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-secret-back
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret-back
                  key: password
          volumeMounts:
            - name: {{ .Values.volumeName }}
              mountPath: /etc/data
      volumes:
        - name: {{ .Values.volumeName }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumeName }}