apiVersion: v1
kind: Namespace
metadata:
  name: back
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: back
    meta.helm.sh/release-namespace: back
    helm.sh/resource-policy: keep