apiVersion: v1
kind: Service
metadata:
  name: service-nodejs
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.app }}
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000