apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{ .Values.volumeName }}
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: /data/my-persistent-data